github_url: https://github.com/indieSoftware/INCommons
author: indie-Software
theme: fullwidth
title: INCommons
module: INCommons
clean: true
output: ./docs
readme: README.md
skip_undocumented: false
hide_documentation_coverage: false
min_acl: public
sdk: iphone
objc: false
swift_build_tool: xcodebuild
xcodebuild_arguments:
  - build
  - -scheme
  - INCommons
  - -destination
  - platform=iOS Simulator,OS=latest,name=iPhone 16
