name: build-and-run-tests
run-name: ${{ github.actor }} runs all tests for branch ${{ github.ref_name }}
on:
  # Trigger when a new pull-request has been opened or a new commit has been pushed for an existing pull-request.
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: macos-13
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: check MacOS version
        run: sw_vers

      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Refer to the correct branch of the pull-request which prevents some problems with dependencies.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build Example App and Run Unit Tests
        run: |
          xcodebuild clean build test \
            -workspace INCommons.xcworkspace \
            -scheme INCommonsExample \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
