#!/bin/sh
# Runs the SwiftFormat on the source code provided by the code path script and returns an error code if formatting is needed.

# Include swift format code path variable.
. config.sh

# Run SwiftFormat in lint mode which returns an exit code we save in a variable.
./Scripts/swiftFormat.sh --lint

# If swift format failed formatting is required.
result=$?
# If result is not 0, it means there was an error.
if [[ $result -gt 0 ]]
then
	# SwiftFormat needs to format anything so print an error message for that.
	echo "Scheme 'Format Code' needs to be run before committing!"
	
fi
exit $result